services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.devcontainer
    container_name: "rss-service"
    volumes:
      - type: bind
        source: ..
        target: /workspace
        consistency: consistent
      - type: bind
        source: /home/brooks/.gitconfig
        target: /root/.gitconfig
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    env_file:
      - ../.env
    command: /bin/sh -c "while sleep 1000; do :; done"
